package demo.employee_task_approval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmpDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "empId")
   private java.lang.String empId;
   @org.kie.api.definition.type.Label(value = "empName")
   private java.lang.String empName;
   @org.kie.api.definition.type.Label(value = "empDept")
   private java.lang.String empDep;
   @org.kie.api.definition.type.Label(value = "empDesignation")
   private java.lang.String empDesignation;

   public EmpDO()
   {
   }

   public java.lang.String getEmpId()
   {
      return this.empId;
   }

   public void setEmpId(java.lang.String empId)
   {
      this.empId = empId;
   }

   public java.lang.String getEmpName()
   {
      return this.empName;
   }

   public void setEmpName(java.lang.String empName)
   {
      this.empName = empName;
   }

   public java.lang.String getEmpDep()
   {
      return this.empDep;
   }

   public void setEmpDep(java.lang.String empDep)
   {
      this.empDep = empDep;
   }

   public java.lang.String getEmpDesignation()
   {
      return this.empDesignation;
   }

   public void setEmpDesignation(java.lang.String empDesignation)
   {
      this.empDesignation = empDesignation;
   }

   public EmpDO(java.lang.String empId, java.lang.String empName,
         java.lang.String empDep, java.lang.String empDesignation)
   {
      this.empId = empId;
      this.empName = empName;
      this.empDep = empDep;
      this.empDesignation = empDesignation;
   }

}