package demo.employee_task_approval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmpDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EmpDO() {
    }

}