package demo.employee_task_approval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("amount")
   private Integer amount;
   @org.kie.api.definition.type.Label("reason")
   private java.lang.String reason;
   @org.kie.api.definition.type.Label("appPriority")
   private java.lang.String appPriority;

   public RequestDO()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.String getAppPriority()
   {
      return this.appPriority;
   }

   public void setAppPriority(java.lang.String appPriority)
   {
      this.appPriority = appPriority;
   }

   public java.lang.Integer getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Integer amount)
   {
      this.amount = amount;
   }

   public RequestDO(java.lang.String name, java.lang.Integer amount,
         java.lang.String reason, java.lang.String appPriority)
   {
      this.name = name;
      this.amount = amount;
      this.reason = reason;
      this.appPriority = appPriority;
   }

}